### PR TITLE
01-05-2021 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging: https://staging.covid19.ca.gov/equity/

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:

- Note concerns or issues here by commenting on this PR

- Work with Triston directly to resolve data issues

- Alert the COVID19 site team in Slack (in the Equity page channel)

### CODE REVIEW

**Comment by aaronhans** [comment]
As of now staging is not yet updated, need to trigger build there to update top boxes, will be done in a couple more minutes

**Comment by aaronhans** [comment]
Updates are reflected in top boxes now

**Comment by coreycaitlin** [comment]
Looks like we have the right number of files, and all the numbers changed. Over to you @sindhuravuri and @vargoCDPH 🎉 

This review did bring up a bug in the "% changed" for the last chart (social determinants). That number represents the change over 30 days, not 7. We're working to fix that ASAP, outside of this pull request.

/cc @hannahslee @m-sullivan7

**Comment by TristonMosbacher** [comment]
The first three top boxes are currently pulling from 1/3 data (should be 1/4).  Confirmed that this was an issue uploading to Snowflake and Thomas has refreshed the tables to contain data from 1/4.  Apologies for not picking that up sooner.

**Comment by coreycaitlin** [comment]
Thanks @TristonMosbacher! @jbum or @aaronhans looks like we need a manual re-run 🔁

**Comment by jbum** [comment]
Doing the manual run now.

**Comment by sindhuravuri** [comment]
Good evening everyone - Here are my notes from today's data review. As always, @vargoCDPH please modify/adjust as you see fit! I sincerely apologize for the late-night delay. 

I only have one main concern I was hoping to request feedback on: I noticed that the statewide case rate in the income chart decreased noticeably from last week (92.5 to 75.6), even though the case rate/100K increased in every R&E category. Does this seem odd at all? I would love to hear your thoughts @TristonMosbacher @vargoCDPH @coreycaitlin? (Additionally, does this issue supplement Jason’s point in the Slack that the 1% value in Blue Box 4 seems off?). Thank you all in advance. 

Otherwise, I don't see any major red flags! 

1. **Blue Box Updates:**
_Summary statement: All values appear reasonable and trends are consistent with previous data._ 

2. **Death Rate/100K by R&E:**
_Summary: We see noticeably large increases in all death/100K rates; all increasing trends, although clearly greater than last week, are reasonable; Multi-Race continues to increase at a fast pace, indicating stabilization of an increasing trend that was observed last week and making AI/AN lowest rate this week. Deaths relative to percentage of population in CA did not change significantly (even unknown); only “Other” and “Unknown” show noticeable (but not alarming) increases — aligns with expectations._

@TristonMosbacher I apologize for the extra question — I just wanted to double confirm, do the rates of increase for Asian American death rate/100K seem reasonable to you (from 7.5 to 10.4)? I wanted to check since this is a larger increase than we have seen in the past for this particular category. 

3. **Case Rate/100K by R&E:**
_Summary statement: We see reasonable increases in all case/100K rates — increasing trends consistent with previous week; ranking of categories remains the same; no significant changes in cases relative to percentage of population in CA._ 

4. **Testing Rate/100K by R&E**
_Summary: Reasonable decreases in all testing/100K rates due to holiday effect; rankings remain the same as last week. Testing relative to percentage of population in CA shows no significant changes._

5. **Mortality rate/100K < Case rate/100K for all categories (as expected)**

6. **Community case rate/100K by median annual household income bracket:**
_Summary: Cases/100K decreased noticeably; 0-40K remains the highest and statewide case rate decreased — point of concern when compared to other case rates/100K (see previous message)_

7. **HE Metric: successfully extended — extension aligns with 7-day lag; reasonable increase in health equity quartile positivity and statewide positivity** 

8. **Data completeness (DC): Deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation — all numbers are reasonable and align with data trends from previous week (see stabilization in GI cases in comparison to last week)**

**Comment by TristonMosbacher** [comment]
Good evening, @sindhuravuri !  Thanks yet again for your thorough analysis.

1.  You're definitely right that the decrease seems odd.  The best reason I can think of is the income chart's statewide value is a 7-day average with a 7-day lag, meaning much of this week's timespan for it is during the holidays.  My guess would be underreporting due to agency closures, although I don't know for certain.  If next week we see an increase to levels at or above last week, that would suggest as much to me, at least.  The cases/100k for R&E cover the previous 30 days, so they are likely less affected by this.

2. Great question about the Asian American death rate.  Numerically it checks out- the count changed from 462 last week to 641 this week.  It appears the increase occurred primarily between 12/29-1/1, and death counts stabilized to mid-600s for the remainder of the week (1/2-1/5).  I can't think of any drivers behind this increase, but it does appear to be present in the data.

**Comment by sindhuravuri** [comment]
> Good evening, @sindhuravuri !  Thanks yet again for your thorough analysis.
> 
> 
> 
> 1.  You're definitely right that the decrease seems odd.  The best reason I can think of is the income chart's statewide value is a 7-day average with a 7-day lag, meaning much of this week's timespan for it is during the holidays.  My guess would be underreporting due to agency closures, although I don't know for certain.  If next week we see an increase to levels at or above last week, that would suggest as much to me, at least.  The cases/100k for R&E cover the previous 30 days, so they are likely less affected by this.
> 
> 
> 
> 2. Great question about the Asian American death rate.  Numerically it checks out- the count changed from 462 last week to 641 this week.  It appears the increase occurred primarily between 12/29-1/1, and death counts stabilized to mid-600s for the remainder of the week (1/2-1/5).  I can't think of any drivers behind this increase, but it does appear to be present in the data.

Thank you so much @TristonMosbacher for taking the time to provide this extremely helpful insight. Based on your advice, I will be sure to keep an eye out for next week's statewide case rate to see if it increases to last week's levels. Regarding 2, thank you for confirming the data! I wonder what the reasons for this increase are. 

Based on Triston's feedback, we are good to go for this PR from my end!

Do we need to wait for any change to the 1% statistic in Blue Box 4?

**Comment by jbum** [comment]
Blue Box 4 was indeed updated by the last manual run.

**Comment by sindhuravuri** [comment]
> Blue Box 4 was indeed updated by the last manual run. 

Thank you @jbum!

**Comment by jbum** [comment]
Closing. Doing a new manual run.

**Pull request closed without merging**
