### PR TITLE
12-16-2020 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by jbum**
Equity dashboard stats updates in this PR may be reviewed on staging: https://staging.covid19.ca.gov/equity/

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:

- Note concerns or issues here by commenting on this PR

- Work with Triston directly to resolve data issues

- Alert the COVID19 site team in Slack (in the Equity page channel)

### CODE REVIEW

**Comment by jbum** [comment]
The automatic Cron failed to create a PR, unclear why. This is a manual run.

**Comment by coreycaitlin** [comment]
This looks 👍  to me:

- 184 files changed, as expected
- Number changes in all charts, as expected
- You can also see the datestamps we added at the chart level 

Over to you @sindhuravuri

**Comment by sindhuravuri** [comment]
Hi everyone! - Here are the notes from today's data review (forgive the length in advance). @vargoCDPH please modify/adjust as you see fit!

Overall, we see some unprecedented rates of increase or decrease in key data, but I do not see any major red flags. Some trends have stabilized (as expected), while others we need to continue to monitor for oscillations. A main concern lies in AI/AN data for deaths/100K (see section 5). 

_General note for Sections 2-4 - NHPI, Black and White are reviewed daily to represent any important changes_ 

**1. Blue Box Updates:**
**_Summary statement: unprecedented decrease in Latino case rate (Box 1) and Median income case rate (Box 4) (greater than previous decreases since 12/11), while PI (Box 2) and Black death rate (Box 3) rates stabilize_** 
1a. Cases/100K values (white text) align with percentages (orange text)
1b. Latino case rate (Box 1): 2% decrease (larger than any previous decrease since 12/11); contrasts with previously observed stabilization to 9%
1c. Pacific Islanders case rate (Box 2): reverts back to stabilized value of 18% (from yesterday’s large increase to 20%)
1d. Black death rate (Box 3): remains stable at 21%
1e. Median income case rate (Box 4): noticeable decrease to 9%, faster rate of decrease than previous 24h

**2. Death Rate/100K by R&E:**
**_Summary statement: Noticeable but reasonable increases in all death/100K rates; we should continue to monitor unstable oscillations in White/NHPI closely_**
2a. Statewide: noticeable increase by .4, deviating from stabilized value of 5.4 from previous 72h
2b. NHPI: Noticeable increase from steady decreases seen over previous 72h 
2b.1 In contrast, % of COVID deaths statewide (yellow bar in deaths relative to percentage of population in CA) for NHPI has remained extremely stable since 12/11  
2b.2 **Something to keep an eye out for: NHPI case rate is down since yesterday while death rate/100K increased**
2c. White: Noticeable — but reasonable — increase
2c.1 This category was steadily rising between 12/11 and 12/14, the only deviation was the decrease seen between 12/14 & 12/15 — therefore, this increase seems reasonable
2c.2 we will continue to monitor and hopefully see stabilization of this trend
2d. Black: increase aligns with stable increases seen since 12/14
2e. Lowest rate: continues to be Multi-Race, which increased by 0.5 in past 24h 

**3. Case Rate/100K by R&E:**
**_Summary statement: Noticeable increases in all case/100K rates (as expected), larger than all 24h rates of increase seen since 12/12; no significant changes in cases relative to percentage of population in CA_**
3a. Statewide: noticeable increase in past 24h, larger than any recent increases since 12/12
3b. NHPI, White, Black: all continue to increase, rate of increase larger than previous 24h
3c. Lowest rate: continues to be Asian-American, for which we see noticeable increase in cases/100K in past 24h 
3d. Cases relative to percentage of population in CA: no significant changes, all numbers are stable; the “Unknown” category continues to see noticeable increases (aligns with previous 48h)

**4. Testing Rate/100K by R&E**
**_Summary statement: Noticeable increases in all testing/100K rates (as expected), fastest rates of increase seen in 72h_** 
4a. Statewide: noticeable increase in past 24h, larger than any recent rates of increase since 12/11
4b. NHPI, White, Black: noticeable increase; larger rate of increase than previous 72h but not completely unreasonable (increasing in testing is expected) 
4c. Lowest rate: continues to be Multi-Race, for which we see noticeable increase in testing/100K in the last 24h 
4d. For testing relative to percentage of population in CA: no significant changes, all numbers are stable

**5. Mortality rate per 100K < case rate per 100K for nearly all categories (as expected)**
5a. I think it is odd that AI/AN has the fourth highest case rate/100K, but 0 deaths/100K (@TristonMosbacher @vargoCDPH, please let me know your thoughts)
5b. We should continue to monitor Asian American vs. Multi-Race categories — Asian American has a lower case rate/100K than Multi-Race but higher death rate/100K — does this seem correct? @vargoCDPH 

**6. Community case rate/100K by median annual household income bracket:**
**_Summary statement: case rate/100K increased noticeably in past 24h, rate of increase larger than any seen since 12/12_** 
6a. increases in 0-40 and 40-60 (both increases larger than any seen since 12/12) 
6b. statewide case rate on social determinants chart increased — aligns with expected

**7. HE Metric: did extend from yesterday, now includes Dec. data points!** 
7a. Noticeable increase in health equity quartile positivity (by .8) and statewide positivity (by .4) — largest rate of increase since 12/12 (statewide positivity only increased at most by .1 in 24h since 12/12, health equity quartile positivity by .3 at most) 

**8. Data completeness changes in past 24h:** 
8a. R&E: data completeness for deaths and cases continues to decrease at similar rate to previous 24h
8b. SO: data completeness for deaths and cases continues to decrease but at higher rate of decrease than previous 24h
8c. GI: data completeness for deaths and cases increases by .1%, in direct contrast to previous decreasing trend seen since 12/13

**Comment by TristonMosbacher** [comment]
Hi @sindhuravuri .  Thanks for the thorough inspection!  

Per 5a (AI/IN mortality rates): The total deaths is too small and is suppressed: The value of the "suppressed" field in the table is "Total" for that entry, meaning a count of 1-10.  I've begun running that portion of the code to see where the actual rate would fall wrt the rest of the mortality rates.

**Comment by coreycaitlin** [comment]
Thanks for weighing in @TristonMosbacher! I'll log that as a usability issue for us to address — I don't think @sindhuravuri will be the only one thrown by those suppressed numbers.

**Comment by TristonMosbacher** [comment]
Appears to be a genuinely low total and mortality rate (lower than all others, but same order of magnitude).  It doesn't seem impossible to me, given the small population size (0.514% of CA pop).  It also depends on where in the 30-day window the cases are most frequent (e.g. if a spike in cases is more recent, deaths may not have had sufficient time to occur).

**Comment by TristonMosbacher** [comment]
Sure thing, @coreycaitlin !

**Comment by sindhuravuri** [comment]
> Appears to be a genuinely low total and mortality rate (lower than all others, but same order of magnitude). It doesn't seem impossible to me, given the small population size (0.514% of CA pop). It also depends on where in the 30-day window the cases are most frequent (e.g. if a spike in cases is more recent, deaths may not have had sufficient time to occur).

Thank you for the explanation @TristonMosbacher ! I agree with you - the low numbers seem reasonable.

**Pull request merged**
