### PR TITLE
12-20-2020 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging: https://staging.covid19.ca.gov/equity/

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:

- Note concerns or issues here by commenting on this PR

- Work with Triston directly to resolve data issues

- Alert the COVID19 site team in Slack (in the Equity page channel)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
I'm seeing the correct number of files changed, and it looks to me like every chart/set of numbers has changed. Keep in mind that the difference between prod and staging is now 3 days' worth of data.

Note: San Diego Health Equity Metric curves still look very strange (though it's starting to move back toward normal-er numbers), as we're still waiting on the datasource to include missing data for that. We have a ticket open for showing a "missing data" message over this chart, just for San Diego. Shouldn't be a blocker for merging this update, as it's not a new issue and this update doesn't make it worse.

@sindhuravuri @vargoCDPH I believe this is ready for review 🎉

**Comment by coreycaitlin** [comment]
Whaddaya think @sindhuravuri and @vargoCDPH? Let us know if you run into any questions with this one.

**Comment by sindhuravuri** [comment]
Hi everyone! - Here are the notes from the 12-20 data review. As always, @vargoCDPH please modify/adjust as you see fit!

**Overall, I don't see any major red flags - I was only surprised by the sharp decrease to 2% from 7% in the Latino case rate (Blue Box 1) in the past 24h. I don't believe this is an issue but I just wanted to confirm if possible - does this number seem reasonable with everyone? @coreycaitlin @TristonMosbacher @vargoCDPH Thank you all in advance!** 

**1. Blue Box Updates:**
**_Summary statement: Case rates all decrease at unprecedented rate (deviate from stabilized values); largest rate of decrease in Latino case rate (Blue Box 1), and death rate for Black people remains stable_**

**2. Death Rate/100K by R&E:**
**_Summary statement: Noticeable increases in all death/100K rates (deviate from stabilized values at unprecedented rate of increase); increasing trends align with expectations; deaths relative to percentage of population in CA did not change significantly (aligns with expected)_**

**3. Case Rate/100K by R&E:**
**_Summary statement: Noticeable but reasonable increases in all case/100K rates, similar to previous sharp rates of increase we have observed in the second half of last week (ranking of Black vs. AI/AN switch); no significant changes in cases relative to percentage of population in CA_**

**4. Testing Rate/100K by R&E**
**_Summary statement: Noticeable increases in all testing/100K rates (as expected), similar sharp rates of increase seen as we have been seeing in past week; category ranking remains the same; testing relative to percentage of population in CA shows no significant changes, all numbers are stable_**

**5. Mortality rate/100K < Case rate/100K for all categories (as expected)**

**6. Community case rate/100K by median annual household income bracket:**
**_Summary statement: Cases/100K increased at unprecedented rate of increase, although not unreasonable; 0-40K remains the highest and statewide case rate increased — aligns with expectations_**

**7. HE Metric: did extend from yesterday**
**_Summary Statement: Noticeable and unprecedented rate of increase in health equity quartile positivity and statewide positivity, but not unreasonable_**

**8. Data completeness: all numbers are reasonable; deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation**

**Comment by coreycaitlin** [comment]
Thank you @sindhuravuri! Let's hold this merge until later today or tomorrow, to avoid any surprises between now and the GO's announcement.

**Comment by coreycaitlin** [comment]
One possible explanation for the decreased disparity in case rates is that the number of cases classified as "unknown" is really going up (likely because testing is happening faster, and race/ethnicity data isn't getting collected as consistently). This may lead to confusing disparity info for cases. Does that seem plausible?

We're looking at replacing that stat with deaths, as data completeness is usually better in that dataset.

**Comment by sindhuravuri** [comment]
> One possible explanation for the decreased disparity in case rates is that the number of cases classified as "unknown" is really going up (likely because testing is happening faster, and race/ethnicity data isn't getting collected as consistently). This may lead to confusing disparity info for cases. Does that seem plausible?
> 
> 
> 
> We're looking at replacing that stat with deaths, as data completeness is usually better in that dataset.

Thanks a lot for the explanation @coreycaitlin - yes this definitely seems plausible in my opinion (and consistent with what we have seen with the unknown category).

**Comment by abquirarte** [comment]
💯

**Pull request closed without merging**
