### PR TITLE
03-02-2021 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging - [here](https://staging.covid19.ca.gov/equity/).

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:
- Note concerns or issues here by commenting on this PR
- Work with Triston directly to resolve data issues
- Alert the COVID19 site team in Slack (in the [Equity page channel](https://cadotgov.slack.com/archives/C01BMCQK0F6))

### CODE REVIEW

**Comment by sindhuravuri** [comment]
Good evening - Here are notes from today's data review. As always, @vargoCDPH please modify/adjust as you see fit!!

:question: I just had a question about Community case rate by median annual household income bracket. This is a visual note — $0-40K and $40-60K are equal in value (11) but the height of the blue bar for $40-60K is lower than the $0-40K bar (see image below)— should they be equal in height? Also, @vargoCDPH, do you agree that these categories being equal is reasonable (I think this is the first time this is the case)? Thank you!

Screen Shot 2021-03-02 at 8 50 12 PM

:heavy_check_mark: Other than this, everything seems normal, and I observe no major red flags!

:bulb: All interesting updates I noticed, but am not concerned about, are listed below for your reference (and also included in my full report below).

- **(Please refer to Section 4)** Two noticeable changes in % of testing statewide were observed as follows:
Latino decreased by ~2% (exactly the same as last week) 
White increased by ~1.5% (exactly the same as last week)

**1. Blue Box Updates:**
:heavy_check_mark: All values remain identical to last week 

**2. Death Rate/100K by R&E:**
:heavy_check_mark: We continue to see decreases in all death/100K rates — all values appear reasonable.

:heavy_check_mark: Deaths relative to percentage of population in CA did not change significantly — Latino & Unknown decreased by ~1% for % of COVID deaths statewide (yellow bar)

**3. Case Rate/100K by R&E:**
:heavy_check_mark: We continue to see noticeable decreases in all case/100K rates, at similar rate of decrease as last week; Asian American continues to be lowest category

:heavy_check_mark: No significant changes in cases relative to percentage of population in CA, most noticeable changes are ~2% decrease and ~1.2% increase for Latino and White, respectively, in % of cases statewide (a reversal in trend for White as compared to last week)

**4. Testing Rate/100K by R&E:**
:heavy_check_mark: All testing/100K rates continue to decrease noticeably, at rates similar to last week, Multi-Race continues to be the lowest category

:heavy_check_mark: Testing relative to percentage of population in CA predominantly showed no significant changes; two noticeable changes in % of testing statewide were observed as follows:
Latino decreased by ~2% (exactly the same as last week) 
White increased by ~1.5% (exactly the same as last week)

**5. Mortality rate/100K vs. Case rate/100K**
:heavy_check_mark: Sanity Check — Mortality rate/100K < Case rate/100K for all categories (as expected)

**6. Community case rate/100K by median annual household income bracket:**
:heavy_check_mark: Cases/100K and statewide case rate both decreased significantly, at rates slower than the previous week (aligns with decrease in Case Rate/100K by R&E); 

:question: $0-40K, for the first time ties with $40-60K — @vargoCDPH just to confirm does this seem reasonable to you?

**7. HE Metric:**
:heavy_check_mark: Line successfully extended; we continue to see consistent, stable rates of decrease in both HE Quartile Positivity and Statewide Positivity; both have been decreasing at extremely steady pace over past three weeks

**8. Data completeness (DC):**
:heavy_check_mark: All values remain predominantly stable/no significant changes — Deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation, as we consistently observe; most noticeable changes are in R&E Deaths DC, which increased by ~1%

**Comment by vargoCDPH** [comment]
That top observation is interesting. As for the identical numbers and different bar heights I defer to @aaronhans 
I think it is possible that these two income bins are very close and it looks like in the last 7 days they are really driving the statewide rate, meaning that most cases are happening among poor.

**Comment by vargoCDPH** [comment]
I checked the data on the rates by income bin and they are both close to 11, with under $40k slightly higher (11.28 vs 10.75)

**Comment by abquirarte** [comment]
Thank you.

~ Angie, from my cell.

**Comment by aaronhans** [comment]
Regarding the different bar heights with identical case numbers:

We are inappropriately rounding the case count in the bar label to an integer. I fixed it to show a single decimal place here https://staging.covid19.ca.gov/equity/

**Comment by hannahslee** [comment]
great catch Sindhu and great fix @aaronhans and thank you! @sindhuravuri can you tag me in these also? thank you!

**Comment by sindhuravuri** [comment]
Thank you all for your help and response!!

@hannahslee Absolutely, will be sure do tag you from now on - apologies for the oversight!

**Pull request merged**
