### PR TITLE
12-22-2020 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging: https://staging.covid19.ca.gov/equity/

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:

- Note concerns or issues here by commenting on this PR

- Work with Triston directly to resolve data issues

- Alert the COVID19 site team in Slack (in the Equity page channel)

### CODE REVIEW

**Comment by abquirarte** [comment]
Are we ready for our first weekly update? I noticed this has not been reviewed yet. @vargoCDPH @coreycaitlin @sindhuravuri  😄

**Comment by coreycaitlin** [comment]
We sure are! Thankfully we've had 3️⃣ uneventful and mostly unsurprising data-update PRs — which we know thanks to @sindhuravuri's careful reviews — so things are looking much more stable.

@sindhuravuri and @vargoCDPH It would be great to get this one merged before noon today if possible, as we expect the Governor to mention the page during his press conference.

**Comment by sindhuravuri** [comment]
> We sure are! Thankfully we've had 3️⃣ uneventful and mostly unsurprising data-update PRs — which we know thanks to @sindhuravuri's careful reviews — so things are looking much more stable.
> 
> 
> 
> @sindhuravuri and @vargoCDPH It would be great to get this one merged before noon today if possible, as we expect the Governor to mention the page during his press conference.

On it @coreycaitlin !

**Comment by sindhuravuri** [comment]
Hi everyone - 

**Overall, I don't see any major red flags! Values are extremely stable; almost all changes align with expectations across all categories, which is great news. I was only surprised by the decreases we see specifically in Multi-Race & White testing/100K, which is what we also saw yesterday (see section 4). While I am not _super_ worried, we are used to seeing increases in all testing categories — if anyone has thoughts on this that would be wonderful and much appreciated! @coreycaitlin @vargoCDPH** 

**Other than that, I think we can go ahead and merge!**

**1. Blue Box Updates:**
_Summary statement: All values stable, no significant changes!_ 

**2. Death Rate/100K by R&E:**
_Summary statement: Statewide death/100K increased; unlike yesterday (where we had some unexpected decreases), we see increases in all death/100K rates — where the increasing trends align with expectations — and White & Black death rates/100K equalizing; deaths relative to percentage of population in CA did not change significantly (aligns with expected) — only unknown category % of statewide deaths decreased noticeably_

**3. Case Rate/100K by R&E:**
_Summary statement: Noticeable but reasonable increases in all case/100K rates, where increasing trends align with expectations (ranking of Black vs. AI/AN switches again); no significant changes in cases relative to percentage of population in CA (aligns with expectations)_

**4. Testing Rate/100K by R&E**
_Summary: Just like yesterday, we see some unexpected decreases — would anyone have any feedback on this?_ 
a. Noticeable increases in some testing/100K rates — statewide, NHPI, Black (as expected), similar sharp rates of increase seen as we have been seeing in past week; however, we also see decreases in Multi-Race & White testing — we usually do not see decreases, what do you think about this @coreycaitlin @vargoCDPH? 
b. Testing relative to percentage of population in CA shows no significant changes, all numbers are stable

**5. Mortality rate/100K < Case rate/100K for all categories (as expected)**

**6. Community case rate/100K by median annual household income bracket:**
_Summary statement: Cases/100K increased reasonably; 0-40K remains the highest and statewide case rate increased — all values align with expectations_

**7. HE Metric: did extend from yesterday by one data point (to Dec. 13); reasonable increase in health equity quartile positivity and statewide positivity — aligns with expectations**

**8. Data completeness (DC): Deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation — all numbers are relatively stable and therefore reasonable; we see almost the exact same trends as yesterday**
a. Small decrease in DC for R&E, GI & SO Deaths, and SO Cases
b. Small increase in DC for R&E & GO Cases & GI Cases

**Comment by coreycaitlin** [comment]
Thanks @sindhuravuri! Over to you for the merge if all looks good @vargoCDPH

**Pull request merged**
