### PR TITLE
Publish PDF history building script

### PR DESCRIPTION
**Pull request by chachasikes**
Hopefully final archiving update of Industry Guidance git history. 
Updated documentation explaining the script and how we used it to create the PDF record.

Will link to this script in documentation.

### CODE REVIEW

**Review by carterm — APPROVED** [review]
Building git history as CSV files to be used by AIrtable

**Review by LizNobriga — APPROVED** [review]

**Comment by chachasikes** [comment]
This was unmerged, fixing that. (Doing github maintenance)

**Comment by jbum** [comment]
Okay to close this, @chachasikes ?

**Comment by jbum** [comment]
Closing this, as it appears to be an abandoned effort.

**Pull request closed without merging**
