### PR TITLE
12-17-2020 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging: https://staging.covid19.ca.gov/equity/

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:

- Note concerns or issues here by commenting on this PR

- Work with Triston directly to resolve data issues

- Alert the COVID19 site team in Slack (in the Equity page channel)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
This has the correct number of files, and I'm seeing updated numbers in all charts. Looks like all went well in terms of retrieving the data. 🎉  Over to you for more thorough review @vargoCDPH!

NB: "Suppressed data" fix is still in development, so those issues are still present here.

**Comment by sindhuravuri** [comment]
Hi everyone! - Here are the notes from today's data review. As always, @vargoCDPH  please modify/adjust as you see fit!

**Overall, extremely similar to yesterday, we see some unprecedented rates of increase in key data; however, no major red flags, especially given that we observed similar trends in the previous 24h. My two main concerns are with the statewide case rate in the social determinants chart (slightly decreased since yesterday despite increases in case/100K rates), and a confirmation request for the slight drop in Multi-Race deaths/100K (see Sections 6c, 2e, respectively) — @TristonMosbacher if possible, could you provide me feedback on this? Thank you in advance!**


_General note for Sections 2-4 - NHPI, Black and White cited as they are reviewed daily to represent any important changes_ 

**1. Blue Box Updates:**
**_Summary statement: Case rates all stable, decrease in Black death rate (Box 3) reasonable given steady decline since 12/11_**

**2. Death Rate/100K by R&E:**
**_Summary statement: Noticeable increases in all death/100K rates (nearly all at faster pace than previous 24h); unstable oscillations in White/NHPI replaced by sharp increases; deaths relative to percentage of population in CA did not change significantly (aligns with expected)_**

2a. Statewide: noticeable increase by .6, greater rate of increase than 24h
2b. NHPI: Noticeable increase, aligns with trend from previous 24h 
2c. White: Noticeable increase — breaks oscillating pattern, but rate of increase largest we’ve seen since 12/11 — **Seeing relative stabilization of this increasing trend is good news**
2d. Black: increase does not align with stable increases seen since 12/14; rather we see noticeable increase — breaks oscillating pattern, but rate of increase largest we’ve seen since 12/11 — **Seeing relative stabilization of this increasing trend is good news**
2e. Lowest rate: continues to be Multi-Race, which, in contrast to increase of 0.5 seen in past 24h, decreases by 0.2 
_**All other categories increased noticeably in deaths/100K, but Multi-race decreased, even though just slightly — I just wanted to double check, does this seem reasonable @TristonMosbacher @vargoCDPH ?**_

**3. Case Rate/100K by R&E:**
**_Summary statement: Noticeable increases in all case/100K rates, similar to sharp 24h rates of increase seen in previous 24h; no significant changes in cases relative to percentage of population in CA_**

3a. Statewide: noticeable increase in past 24h, similar to previous 24h
3b. NHPI, White, Black: all continue to increase, rate of increase similar to previous 24h
3c. Lowest rate: continues to be Asian-American, for which we see similar rate of increase in cases/100K as previous 24h 
3d. For cases relative to percentage of population in CA: no significant changes — I did notice that, for the first time I have ever seen, the “Unknown” category decreased rather than increased — however, not by an unreasonable number (need to continue to monitor for any sharp oscillations)

**4. Testing Rate/100K by R&E**
**_Summary statement: Noticeable increases in all testing/100K rates (as expected), similar sharp rates of increase seen as previous 24h_** 

4a. Statewide: noticeable increase in past 24h, similar to rates of increase seen in previous 24h
4b. NHPI: noticeable increase; larger rate of increase than previous 24h but not completely unreasonable (increasing in testing is expected) 
4c. White, Black: noticeable increase; similar rate of increase seen as previous 24h
4d. Lowest rate: continues to be Multi-Race, for which we see noticeable increase in testing/100K in the last 24h — faster rate of increase than previous 24h
4e. For testing relative to percentage of population in CA: no significant changes, all numbers are stable

**5. Mortality rate per 100K < case rate per 100K for nearly all categories (as expected)**

**6. Community case rate/100K by median annual household income bracket:**
**_Summary statement: case rate/100K increased noticeably in past 24h, rate of increase similar to previous 24h; statewide case rate decreased (does not align with expectations)_** 
6a. Statewide case rate on social determinants chart slightly decreased, although noticeable increases in nearly all other case rates/100K —  @TristonMosbacher what do you think about this?
6b. 0-40 highest, aligns with expectations

**7. HE Metric: did extend from yesterday!** 
7a. Noticeable increase in health equity quartile positivity and statewide positivity, but at same pace as previous 24h

**8. Data completeness: All data aligns with previous trends in increase/decrease, no significant changes or anomalies**

**Comment by TristonMosbacher** [comment]
Thanks again for the thorough inspection, @sindhuravuri !

1.  I've been comparing the statewide rate against the snapshot dashboard (see "Case rate per 100,000 per day, excl. prisoners (7 day avg, 7 day lag), and they're the same at 69.6.  I feel fairly confident that's reflective of a true decrease versus yesterday.

2.  The counts for multi-race deaths are 29 for the past 30 days, 26 for the previous 30 before that.  Total deaths (with known r/e) for those two time periods are 2,585 and 1,408, respectively.  Thus the % of deaths for multi-racial is 1.1%, while it was 1.8%.  It's more that the % increase of multi-racial deaths (+11.5%) has been outpaced by total deaths (+83.6%).

Hope that helps!

**Comment by sindhuravuri** [comment]
> Thanks again for the thorough inspection, @sindhuravuri !
> 
> 
> 
> 1.  I've been comparing the statewide rate against the snapshot dashboard (see "Case rate per 100,000 per day, excl. prisoners (7 day avg, 7 day lag), and they're the same at 69.6.  I feel fairly confident that's reflective of a true decrease versus yesterday.
> 
> 
> 
> 2.  The counts for multi-race deaths are 29 for the past 30 days, 26 for the previous 30 before that.  Total deaths (with known r/e) for those two time periods are 2,585 and 1,408, respectively.  Thus the % of deaths for multi-racial is 1.1%, while it was 1.8%.  It's more that the % increase of multi-racial deaths (+11.5%) has been outpaced by total deaths (+83.6%).
> 
> 
> 
> Hope that helps!


It absolutely does! Thanks so much again for the clarifications @TristonMosbacher. I see no further issues for today then on my end!

**Pull request merged**
