### PR TITLE
03/07/2021 Vaccine HPI

### PR DESCRIPTION
**Pull request by aaronhans**

### CODE REVIEW

**Comment by aaronhans** [comment]
Per Hannah:

Back of envelope math shows we have too many data points in the top chart, vaccinations should represent the 7M people vaccinated not the 10M shots given

**Comment by aaronhans** [comment]
SQL change to generate this is here: https://github.com/cagov/Cron/pull/106

**Comment by carterm** [comment]
Replaced with ... https://github.com/cagov/covid-static/pull/269

**Comment by carterm** [comment]
obsolete

**Pull request closed without merging**
