### PR TITLE
02-16-2021 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging - [here](https://staging.covid19.ca.gov/equity/).

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:
- Note concerns or issues here by commenting on this PR
- Work with Triston directly to resolve data issues
- Alert the COVID19 site team in Slack (in the [Equity page channel](https://cadotgov.slack.com/archives/C01BMCQK0F6))

### CODE REVIEW

**Comment by vargovargo** [comment]
I can't say that I did as thorough a review as @sindhuravuri but it looks good to me. The rates are overall down. Maybe the biggest change is the % of statewide deaths that are AIAN (0.3% to 0.5%), some additional deaths among that population likely changed the order of the R/E groups in that chart.

**Comment by vargovargo** [comment]
Also, I think @sindhuravuri is out this week, so I would merge this PR without her review if possible.

**Comment by vargoCDPH** [comment]
sorry, looks like I submitted those comments under the wrong github account.

**Comment by abquirarte** [comment]
LOL. Thank you @vargoCDPH

**Comment by sindhuravuri** [comment]
Here are notes from today's data review! Included for the record. Sincerely, sincerely sorry for the delay. Thank you so much @vargoCDPH for taking care of the merge!

:heavy_check_mark: Everything seemed normal, and I observed no major red flags!

:bulb: Some interesting updates I noticed, are listed below for reference (and also included in my full report below).

- **(Please refer to Section 1)** Case rate for Pacific Islanders (Blue Box 2) increases again after last week’s noticeable decrease (returning to increasing trend we have seen since 1/06/21), death rate for Black people (Blue Box 3) is lowest we have seen, case rate for communities with median income (Blue Box 4) remains unchanged. 
- **(Please refer to Section 2)** We see noticeable decreases in almost all death/100K rates, at rates slower than last week. Unlike last week, Multi-Race also decreases by 3. It is important to note AI/AN continues to increase, will continue to monitor. 
- **(Please refer to Section 3)**We continue to see decreases in all case/100K rates, at noticeably slower rates than the drops we observed last week (or the previous week); Asian American continues to be lowest rate
- **(Please refer to Section 6)** Cases/100K and statewide case rate both continue to decrease, at slower rates of decrease than last week (aligns with decrease in Case Rate/100K by R&E); $0-40K remains highest in cases/100K (as expected)
- **(Please refer to Section 7)** Both HE Quartile Positivity and Statewide Positivity reasonably decrease, at slower rates than last week but numbers are consistent with recent trends

**1. Blue Box Updates:**
:heavy_check_mark: All values appear reasonable — case rate for Pacific Islanders (Blue Box 2) increases again after last week’s noticeable decrease (returning to increasing trend we have seen since 1/06/21), death rate for Black people (Blue Box 3) is lowest we have seen, case rate for communities with median income (Blue Box 4) remains unchanged. 

**2. Death Rate/100K by R&E:**
:heavy_check_mark: We see noticeable decreases in almost all death/100K rates, at rates slower than last week. Unlike last week, Multi-Race also decreases by 3. Only AI/AN continues to increase, will continue to monitor. 

**3. Case Rate/100K by R&E:**
:heavy_check_mark: We continue to see decreases in all case/100K rates, at noticeably slower rates than the drops we observed last week (or the previous week); Asian American continues to be lowest rate

**4. Testing Rate/100K by R&E:**
:heavy_check_mark: All testing/100K rates decreased noticeably, at rates similar to last week. Multi-Race continues to be lowest rate. 

**5. Mortality rate/100K vs. Case rate/100K**
:heavy_check_mark: Sanity Check — Mortality rate/100K < Case rate/100K for all categories (as expected)

**6. Community case rate/100K by median annual household income bracket:**
:heavy_check_mark: Cases/100K and statewide case rate both continue to decrease, at slower rates of decrease than last week (aligns with decrease in Case Rate/100K by R&E); $0-40K remains highest in cases/100K (as expected)

**7. HE Metric:**
:heavy_check_mark: Successfully extended — extension aligns with 7-day lag; both HE Quartile Positivity and Statewide Positivity reasonably decrease, at slower rates than last week but numbers are consistent with recent trends

**8. Data completeness (DC):**
:heavy_check_mark: All DC values are reasonable with the following differences:
R&E DC — Deaths remain unchanged (unlike increase we saw last week), Cases increased by .7%
SO Deaths and Cases DC increases by .4 and ~2%, respectively
GI Deaths DC decreases by .1% and Cases DC increases by .4%

:heavy_check_mark: Deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation, as we consistently observe

**Pull request merged**
