### PR TITLE
12-12-2020 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging: https://staging.covid19.ca.gov/equity/

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:

- Note concerns or issues here by commenting on this PR

- Work with Triston directly to resolve data issues

- Alert the COVID19 site team in Slack (in the Equity page channel)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
@aaronhans @vargoCDPH Couple things to note:

- Seeing no change in the top summary boxes (prod and staging have the same numbers, which is fishy) 🤔 
- All other charts have changes, as expected ✔️ 
- The bottom charts (factors that increase risk) show the biggest jump, by far — I assume this is because they're the only ones with a 7-day timeframe instead of a 30-day timeframe, but please take an extra look there 📊

**Comment by vargoCDPH** [comment]
I suspect that third point is correct.

Jason Vargo
916-694-7435
Jason.Vargo@cdph.ca.gov
CovModeling@cdph.ca.gov
________________________________

**Comment by abquirarte** [comment]
We may want to fix this minor thing too.
Using Chrome on Samsung S10.

**Comment by abquirarte** [comment]
More crowded here :) (no pun intended).

**Comment by coreycaitlin** [comment]
@abquirarte  I'll capture that mobile layout bug in Jira!

**Comment by sindhuravuri** [comment]
Hi everyone! - Below is brief summary from today's data review. 

1. Statewide death rates (Deaths relative to percentage of population in California) did not change significantly — NA/PI stayed the same (aligns with expectations)
2. Statewide case rate (Cases relative to percentage of population in California) did not change significantly (aligns with expectations)
        1. Only the unknown category had a 9.0% increase since the previous month 
3. Testing/100K increased (aligns with expectations)
4. Mortality rate per 100K < Case rate per 100K (aligns with expectations)
        1. Potential (minor) discrepancy: I don’t see a yellow bar for AI/AN for Deaths relative to percentage of population in California
5. HE metric: did not extend from yesterday 
6. Data completeness: Deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation
7. 0-40K was the highest for community case rate by median annual household income bracket (aligns with expectations)

**Comment by coreycaitlin** [comment]
@sindhuravuri Thank you! That all sounds good...any red flags? Anything look dramatically wrong?

**Comment by coreycaitlin** [comment]
Holding until we resolve (or at least understand) two issues:

- Top boxes' data not changing
- Missing missingness files (try saying that one 10 times fast)

**Comment by vargoCDPH** [comment]
I think 4 .1 ([up here](https://github.com/cagov/covid-static/pull/27#issuecomment-743945407)) was the only question we had

**Comment by coreycaitlin** [comment]
Ok — for 4.1, possible explanations include:

- No AI/AN deaths recorded in past 30 days?
- Any deaths among this demographic were recorded as "Other" or "Unknown"?
- Fewer than 11 led to data suppression [I'd need to dig to see if this is even a thing at this level]?

Do those seem plausible? Or does this look like it's further off-base than that?

**Comment by vargoCDPH** [comment]
I think it's 0 deaths for AI/AN.  So the data seems good. 
Should we think about adding a more descriptive note when this happens.

**Comment by coreycaitlin** [comment]
yeah, that's a great point. The tooltip doesn't really make sense when the data == 0. I'll add an issue for improving that user-facing language.

**Comment by coreycaitlin** [comment]
I'm closing out this PR in favor of #28, which includes fresh missingness data.

**Pull request closed without merging**
