### PR TITLE
01-19-2021 equity dashboard chart data update

### PR DESCRIPTION
**Pull request by wpserviceuser**
Equity dashboard stats updates in this PR may be reviewed on staging - [here](https://staging.covid19.ca.gov/equity/).

After reviewing, if all looks well, approve and merge this Pull Request.

If there are issues with the data:
- Note concerns or issues here by commenting on this PR
- Work with Triston directly to resolve data issues
- Alert the COVID19 site team in Slack (in the [Equity page channel](https://cadotgov.slack.com/archives/C01BMCQK0F6))

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Looks like everything ran as expected! @sindhuravuri, wanna take a look?

/cc @hannahslee

**Comment by sindhuravuri** [comment]
On it now @coreycaitlin !

**Comment by sindhuravuri** [comment]
Good evening everyone - Here are notes from today's data review. As always, @vargoCDPH please modify/adjust as you see fit!

:question: **(Please refer to sections 2 & 6 below)** My main questions are in regards to the Death Rate/100K for AI/AN & Multi-Race, as well as the Community case rate/100K by median annual household income bracket. If possible, I would very much love to hear your thoughts @TristonMosbacher @vargoCDPH  — thank you in advance!

:heavy_check_mark: Everything else seems normal, and I observe no major red flags. 

:bulb: Finally, some interesting updates I noticed, but am not concerned about, are listed below for your reference (and also included in my full report below).

- **(Please refer to Section 4)** NHPI testing/100K increased significantly, in comparison to other categories (which remain relatively stable in increase rate). 
- **(Please refer to Section 4)** For % of testing statewide, there is a 1.5% increase for Latino and a 1.6% decrease for White; this is directly inverse to last week’s trend, which was as follows — “a pronounced decrease for White and increase for Latino in % of testing statewide than previous weeks”;  there is also a 3% decrease in “Unknown.”
- **(Please refer to Sections 2 & 3)** The “Unknown” category shows a 2% increase in deaths relative to percentage of population in CA and a 4% decrease in case rate/100K, identical to last week.

Thank you all again!

**1. Blue Box Updates:**
:heavy_check_mark: All values appear reasonable, and trends are consistent with previous data.

**2. Death Rate/100K by R&E:**
:question: We see noticeably large increases in nearly all death/100K rates; AI/AN remains lowest rate. In contrast, AI/AN decreases, while Multi-Race does not change at all — if possible, I wanted to double check with you that the trends for AI/AN and Multi-Race seem reasonable/accurate @TristonMosbacher @vargoCDPH?

:heavy_check_mark: Deaths relative to percentage of population in CA did not change significantly, except for the “Unknown” category. “Unknown” shows a nearly 2% increase, like last week (not unreasonable). “Latino” shows 1% increase.  

**3. Case Rate/100K by R&E:**
:heavy_check_mark: We see greater increases in all case/100K rates than last week, as expected — increasing trends are small, but reasonable.

:heavy_check_mark: No significant changes in cases relative to percentage of population in CA, except (like with Death Rate/100K) in the “Unknown” category. “Unknown” shows a nearly 4% decrease (not unreasonable), like last week. 

**4. Testing Rate/100K by R&E:**
:heavy_check_mark: All testing/100K increase reasonably, as expected; NHPI increased significantly, while other categories remain relatively stable in increase rate. 

:heavy_check_mark: Testing relative to percentage of population in CA showed no significant changes to be concerned about (for % of testing statewide, there is a 1.5% increase for Latino and a 1.6% decrease for White; this is directly inverse to last week’s trend — “a pronounced decrease for White and increase for Latino in % of testing statewide than previous weeks”). There is a 3% decrease in “Unknown.”

**5. Mortality rate/100K vs. Case rate/100K**
:heavy_check_mark: Mortality rate/100K < Case rate/100K for all categories (as expected)

**6. Community case rate/100K by median annual household income bracket:**
:question: Cases/100K in $40-60K showed decrease (although small) — we usually see increases in this category (we see increases in statewide case rate & $0-40K this week as well) — although the decrease is small, I just wanted to double check that this seems reasonable/accurate @TristonMosbacher @vargoCDPH? 

:heavy_check_mark: Cases/100K in $0-40K showed small increase, and statewide case rate increased, as expected

**7. HE Metric:**
:heavy_check_mark: Successfully extended — extension aligns with 7-day lag; we observe a noticeable decrease in both HE Quartile Positivity and Statewide Positivity

**8. Data completeness (DC):**
:heavy_check_mark: Deaths are the most complete for race/ethnicity and gender identity, not for sexual orientation, as we consistently observe; values generally reasonable
- R&E: DC for Deaths recovers from last week’s noticeable decrease (back to stabilized values from 1/06 and before); Cases noticeably increases (consistent with what we saw between 1/06 and 1/12); 
- SO: Small decrease in DC for Deaths, and small increase in DC for Cases
- GI: Small decrease in DC for Deaths, and ~1.7% decrease in DC for Cases

**Comment by vargoCDPH** [comment]
regarding #2 above ^^^^ this seems reasonable, since we are experiencing slightly slowing case (maybe peaking) with sustained ICU surge and deaths lag in cases.  
for # 6 I am surprised that the state rate is edging closer and closer to the rate in the poorest communities, but the changes don't signal anything out of the ordinary.

**Pull request merged**
